---
# vars file for docker

_docker_packages:
  default:
    - docker
  Debian:
    - docker.io
    - python3-docker
  RedHat-7:
    - docker-io
  RedHat:
    - moby-engine

docker_packages: "{{ _docker_packages[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_docker_packages[ansible_os_family] | default(_docker_packages['default'] )) }}"

_docker_pip_packages:
  default:
    - docker
  Debian: []

docker_pip_packages: "{{ _docker_pip_packages[ansible_os_family] | default(_docker_pip_packages['default']) }}"

_docker_ppa_arch:
  default: amd64
  aarch64: arm64
  x86_64: amd64
docker_ppa_arch: "{{ _docker_ppa_arch[ansible_architecture] | default(_docker_ppa_arch['default']) }}"
