# setting for ansible
bootstrap_wait_for_host: true
ansible_user: root

# the user name we use to install the iracelog software
username: "{{ vault_username }}"

# settings for user
users_group_list:
  - name: "{{ username }}"
  - name: users

users_user_list:
  - name: "{{ username }}"
    group: "{{ username }}"
    groups:
      - users
    sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    authorized_keys:
      - "{{ vault_hetzner_public_key }}"

# settings for auto_update
auto_update_apply_updates: yes

# locale settings
locale_lang: en_US.UTF-8
locale_timezone: Europe/Berlin

# settings for ssh
openssh_password_authentication: "no"

# settings for firewall
firewall_services:
  - name: ssh
  - name: http
  - name: https

# settings for docker
docker_privileged_users:
  - "{{ username }}"

# settings for iracelog
main_domain: "{{ vault_main_domain }}"
iracelog_iwr_version: v0.0.2
iracelog_ism_version: v0.6.1
iracelog_ism_go_version: v0.16.1
iracelog_ias_version: v0.3.1
iracelog_frontend_version: v0.26.0
iracelog_graphql_version: v0.4.0
