# used from https://gitlab.com/djpic/docker-images/-/blob/master/Traefik/tls/traefik_dynamic.yml
# Blog: https://www.djpic.net/articles/traefik-v2-secure-tls-and-header-configuration-with-docker-provider/
tls:
  options:
    # Set default for a minimum of TLS v1.2 with the most secure ciphers; the browser can negotiate to TLS v1.3 if preferred.
    default:
      minVersion: VersionTLS12      
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_AES_256_GCM_SHA384
        - TLS_AES_128_GCM_SHA256
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_FALLBACK_SCSV
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: false
    # Custom option for only TLS v1.3; if browser does not support TLS v1.3, the page will fail to load.
    tlsv13only:
      minVersion: VersionTLS13

http:
  middlewares:
    mp-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserxssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # Enabled Secure headers
    secure-headers:
      headers:
        sslRedirect: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserxssfilter: true
        accessControlAllowMethods:
          - GET
          - POST
        accessControlMaxAge: 100
        addVaryheader: true
        contentSecurityPolicy: script-src 'self'
        referrerPolicy: origin-when-cross-origin

    # Semi Secure Headers to allow custom contentSecurityPolicy
    semi-secure-headers:
      headers:
        sslRedirect: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        contentTypeNosniff: true
        accessControlAllowMethods:
          - GET
          - POST
        accessControlMaxAge: 100
        addVaryheader: true
        referrerPolicy: origin-when-cross-origin

    # Allow compressed content
    compress-content:
      compress: {}
