- name: Common server configuration
  hosts: prod
  become: true
  gather_facts: true
  roles:
    - robertdebock.roles.bootstrap
    - robertdebock.roles.core_dependencies
    - robertdebock.roles.locale
    - robertdebock.roles.buildtools
    - robertdebock.roles.epel
    - robertdebock.roles.users
    - robertdebock.roles.software
    - robertdebock.roles.fail2ban
    - robertdebock.roles.openssh
    - robertdebock.roles.firewall
    - robertdebock.roles.auto_update
    - robertdebock.roles.update
    - tools/docker
    - tools/traefik
    - apps/iracelog
