- name: Common server configuration 
  hosts: prod
  become: true
  gather_facts: false
  roles:
    - robertdebock.roles.bootstrap
    - robertdebock.roles.core_dependencies
    - robertdebock.roles.buildtools
    - robertdebock.roles.epel
    - robertdebock.roles.python_pip
    - robertdebock.roles.users
    - robertdebock.roles.software
    - robertdebock.roles.fail2ban
    - robertdebock.roles.openssh
    - robertdebock.roles.firewall
    - robertdebock.roles.auto_update    
    - robertdebock.roles.update    
    - robertdebock.roles.docker
    - robertdebock.roles.docker_compose    
    - tools/traefik
    - apps/iracelog
