- name: Common server configuration
  hosts: prod
  become: true
  gather_facts: true
  roles:
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.locale
    - robertdebock.buildtools
    - robertdebock.epel
    - robertdebock.users
    - robertdebock.software
    - robertdebock.fail2ban
    - robertdebock.openssh
    - robertdebock.firewall
    - robertdebock.auto_update
    - robertdebock.update
    - tools/docker
    - tools/traefik
    - apps/iracelog
