- name: Order servers
  hosts: localhost
  gather_facts: false

  roles:
    - hetzner/create

  tasks:
    - name: create local hosts file
      template: src=../hosts.yml.sample dest=../hosts.yml

  vars:
    hetzner_order_server_list:
      - hostname: server
        server_type: cx21
        subdomains:
          - server
          - traefik
          - iracelog
          - crossbar
          - graphql
