- name: Remove servers
  hosts: localhost
  gather_facts: false

  roles:
    - hetzner/remove

  vars:
    hetzner_remove_server_list:
      - hostname: server
        server_type: cx22
        subdomains:
          - server
          - traefik
          - iracelog
          - grpc
          - graphql
