- name: Update iraclog installation
  hosts: prod
  become: true
  gather_facts: false
  # vars_files:
  #  - vars/vault.yml
  #  - vars/default.yml
  roles:
    - "apps/iracelog-down"
    - apps/iracelog
